services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "5173:5173"
    volumes:
      - ./:/frontend/
      - /frontend/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - hack_and_play_network

networks:
  hack_and_play_network:
    name: hack_and_play_network
