from enum import Enum


class Daypart(str, Enum):
    MORNING = "MORNING"
    NOON = "NOON"
    EVENING = "EVENING"
    NIGHT = "NIGHT"

class DistrictType(str, Enum):
    BEDROOM = "BEDROOM"
    FAMILY = "FAMILY"
    OFFICE = "OFFICE"
    MIXED = "MIXED"
    OTHER = "OTHER"

class IndicatorKind(str, Enum):
    DEVICE_COUNT = "DEVICE_COUNT"
    DATA_TRANSFER_BYTES = "DATA_TRANSFER_BYTES"
    PRESENCE_COUNT = "PRESENCE_COUNT"
    GREEN_PRESENCE_RATIO = "GREEN_PRESENCE_RATIO"
    DIGITAL_NOISE_SCORE = "DIGITAL_NOISE_SCORE"
    SOCIAL_ACCESSIBILITY_SCORE = "SOCIAL_ACCESSIBILITY_SCORE"
    LIFE_BALANCE_SCORE = "LIFE_BALANCE_SCORE"
    SAFETY_REPORTS_COUNT = "SAFETY_REPORTS_COUNT"
