namespace: "fastmove"
domain: "idk-hackplay.pl"

api:
  appName: api
  replicas: 2
  image:
    name: rg.pl-waw.scw.cloud/namespace-thirsty-hofstadter/api
    tag: latest
  resources:
    requests:
      memory: 512Mi
      cpu: 512m
    limits:
      memory: 1Gi
      cpu: 1
  hpa:
    minReplicas: 2
    maxReplicas: 10
    cpuTarget: 60
