name: build-and-push
on:
  push:
    paths:
      - "backend/**"
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: aks-runners
    permissions:
      contents: write
    env:
      REGISTRY: ${{ secrets.SCW_REGISTRY }}
      NAMESPACE: ${{ secrets.SCW_NAMESPACE }}
      IMAGE: api
      TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Parse SCR host/namespace from secret
        run: |
          FULL="${{ secrets.SCW_REGISTRY }}"              # np. rg.pl-waw.scw.cloud/namespace-thirsty-hofstadter
          HOST="${FULL%%/*}"
          NS="${FULL#*/}"
          echo "REGISTRY=$HOST" >> $GITHUB_ENV
          echo "NAMESPACE=$NS" >> $GITHUB_ENV   

      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY }}
          username: nologin
          password: ${{ secrets.SCW_SECRET_KEY }}

      - name: Build and push (backend/Dockerfile)
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            rg.pl-waw.scw.cloud/namespace-thirsty-hofstadter/api:${{ env.TAG }}
          cache-from: type=registry,ref=rg.pl-waw.scw.cloud/namespace-thirsty-hofstadter/api:buildcache
          cache-to: type=registry,ref=rg.pl-waw.scw.cloud/namespace-thirsty-hofstadter/api:buildcache,mode=max

      - name: Tag latest (only master)
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          docker build -f backend/Dockerfile -t rg.pl-waw.scw.cloud/namespace-thirsty-hofstadter/api:latest backend
          docker push rg.pl-waw.scw.cloud/namespace-thirsty-hofstadter/api:latest

      - name: Update image tag in values.yaml and commit
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          sed -i "s|^  tag: .*|  tag: \"rg.pl-waw.scw.cloud/namespace-thirsty-hofstadter/api:${TAG}\"|" infra/charts/api/values.yaml
          
          git add infra/charts/api/values.yaml
          git commit -m "chore(ci): update image tag to ${TAG}"
          git push